pipelines:
  default:
    - step:
        name: Build and Push Docker Image
        image: docker:23.0.1
        services:
          - docker
        script:
          - export IMAGE_NAME=daudidrees/3-tier-ap:${BITBUCKET_COMMIT}
          # Build the Docker image
          - docker build -t $IMAGE_NAME .
          # Log in to Docker Hub
          - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          # Push the Docker image
          - docker push $IMAGE_NAME
        artifacts:
          - image.tar # Optional: Export built image if needed locally
    - step:
        name: Update and Push Deployment Manifest
        image: alpine/git
        script:
          - git clone https://daudkhan37:${APP_PASSWORD}@bitbucket.org/my-devops-world/cd-cd-gitops.git
          - cd cd-cd-gitops
          - sed -i "s/3-tier-ap:[0-9]*\|3-tier-ap:v1/3-tier-ap:${BITBUCKET_BUILD_NUMBER}/" deployment.yml
          - git config --global user.email "jhonsdavid37@gmail.com"
          - git config --global user.name "daudkhan37 "
          - git add deployment.yml
          - git commit -m "Update deployment.yml with build ${BITBUCKET_BUILD_NUMBER}"
          - git push origin main