apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskdemo
  template:
    metadata:
      labels:
        app: flaskdemo
    spec:
      containers:
      - name: flaskdemo
        image: daudidrees/githubaction-flask:dc52515e856e046a690a4883869171208535bcaf
        ports:
        - containerPort: 5000  # Expose the port your Flask app listens on
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: flask-node-port-svc
spec:
  type: NodePort
  selector:
    app: flaskdemo
  ports:
  - port: 80       # Port accessible from outside the cluster
    targetPort: 5000  # Port the container is listening on
    nodePort: 30007 # Port on each node that forwards to the container