name: Build and Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'deployment.yml'

jobs:
  build-and-push-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          export IMAGE_NAME=daudidrees/githubaction-flask:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  update-and-push-deployment-manifest:
    name: Update and Push Deployment Manifest
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Skip workflow if triggered by Actions
        run: |
          if [[ "$(git log -1 --pretty=%an)" == "github-actions[bot]" ]]; then
            echo "Skipping workflow as it was triggered by a bot commit."
            exit 0
          fi

      - name: Update deployment manifest
        run: |
          git clone https://github.com/Daudkhan1/cd-cd-gitops.git
          cd cd-cd-gitops
          sed -i "s|image: .*|image: daudidrees/githubaction-flask:${{ github.sha }}|" deployment.yml
          git config --global user.email "daudidrees1024@gmail.com"
          git config --global user.name "Daudkhan1"
          git add deployment.yml
          git commit -m "Update deployment.yml with build ${{ github.run_number }}"
          git push https://${{ secrets.GH_PAT }}@github.com/Daudkhan1/cd-cd-gitops.git main
