name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Tag for the Docker image'
        required: true
        default: 'v1'

jobs:
  build-and-push-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          export IMAGE_NAME=daudidrees/githubaction-flask:${{ github.event.inputs.docker_tag }}
          # Build Docker image
          docker build -t $IMAGE_NAME .
          # Push Docker image
          docker push $IMAGE_NAME

  update-and-push-deployment-manifest:
    name: Update and Push Deployment Manifest
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update deployment manifest
        run: |
          git clone https://github.com/Daudkhan1/cd-cd-gitops.git
          cd cd-cd-gitops
          sed -i "s|daudidrees/3-tier-ap:[0-9]*\|daudidrees/3-tier-ap:v[0-9]*|daudidrees/githubaction-flask:${{ github.event.inputs.docker_tag }}|" deployment.yml

          # Check for changes before committing
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git config --global user.email "daudidrees1024@gmail.com"
          git config --global user.name "Daudkhan1"
          git add deployment.yml
          git commit -m "Update deployment.yml with tag ${{ github.event.inputs.docker_tag }}"
          git push https://${{ secrets.GH_PAT }}@github.com/Daudkhan1/cd-cd-gitops.git main
